name: Down To Reiki!
favicon: null
layout_spectrum: 0.30080866534262896
typography_spectrum: 0.395587440347299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.46420026291161776
  lightness: 0.4116570802871138
  saturation: 0.2062631722074002
  rhythmicContrast: 0.8557744037825614
purpose: []
